config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  concern :uploadable do
    resources :uploads, only: [:new, :create]
  end

  concern :messageable do
    resources :messages
  end

  concern :reviewable do
    resource :review, only: [:new, :create, :edit, :update, :destroy]
  end

  def api_endpoints
    devise_for :users, controllers: { registrations: 'api/v1/users/registrations',
                                           sessions: 'api/v1/sessions' }

    devise_for :contractors, controllers: { registrations: 'api/v1/contractors/registrations',
                                                 sessions: 'api/v1/sessions' }

    concern :reviewable do
      resource :review, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :contractors, only: [:index, :show] do
      resource :gallery, only: :show
    end

    resources :users, only: [:show],
                  concerns: [:uploadable, :messageable],
                  defaults: { uploadable: 'user',
                             messageable: 'user' }

    resources :jobs, concerns: [:uploadable, :reviewable],
                     defaults: { uploadable: 'job',
                   reviewable: 'job' } do
      resources :bids, only: [:create, :show, :update, :destroy]
      resource :review
    end

    resources :examples, concerns: [:uploadable],
                         defaults: { uploadable: 'example' }

    resource :search, only: :create

    devise_scope :user do
      match 'users/token_reset' => 'sessions#token_reset', via: :post
    end

    devise_scope :contractor do
      match 'contractors/token_reset' => 'sessions#token_reset', via: :post
    end

    match 'categories' => 'contractors#categories', as: 'contractor_categories', via: :get
    match 'bids/:id/accept' => 'bids#accept_bid', as: 'accept_bid', via: :post
    match 'bids/:id/reject' => 'bids#reject_bid', as: 'reject_bid', via: :post
    match 'jobs/:id/resume_search' => 'jobs#resume_search', as: 'resume_search', via: :post
    match 'jobs/:id/cancel_job' => 'jobs#cancel_job', as: 'cancel_job', via: :post
    match 'jobs/:id/mark_as_complete' => 'jobs#mark_as_complete', as: 'mark_as_complete', via: :post
  end

  if Rails.env.staging?
    namespace :api, path: '/', constraints: { subdomain: 'api.staging' }, defaults: { format: :json } do
      namespace :v1 do
        api_endpoints
      end
    end
  else
    namespace :api, path: '/', constraints: { subdomain: 'api' }, defaults: { format: :json } do
      namespace :v1 do
        api_endpoints
      end
    end
  end

	devise_for :users, controllers: { registrations: 'users/registrations',
                                         sessions: 'sessions' }

	devise_for :contractors, controllers: { registrations: 'contractors/registrations',
                                               sessions: 'sessions' }

  resources :users, only: [:show],
                concerns: [:uploadable, :messageable],
                defaults: { uploadable: 'user', messageable: 'user' }

  resources :contractors, only: [:show, :index],
                      concerns: [:uploadable, :messageable],
                      defaults: { uploadable: 'contractor', messageable: 'contractor' } do
    resource :gallery, only: :show
  end

  resources :jobs, concerns: [:uploadable, :reviewable],
                   defaults: { uploadable: 'job',
                               reviewable: 'job' } do
    resources :bids, only: [:create, :show, :update, :destroy]
    resource :review
  end

  resources :examples, concerns: [:uploadable],
                       defaults: { uploadable: 'example' }

  resources :uploads, only: :destroy

  resources :bids, only: :destroy

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :sentbox
      get :trashbin
      post :empty_trash
    end
  end

  resource :contact, only: [:new, :create]
  resource :search, only: :show

  match 'bids/:id/accept' => 'bids#accept_bid', as: 'accept_bid', via: :post
  match 'bids/:id/reject' => 'bids#reject_bid', as: 'reject_bid', via: :post
  match 'jobs/:id/resume_search' => 'jobs#resume_search', as: 'resume_search', via: :post
  match 'jobs/:id/cancel_job' => 'jobs#cancel_job', as: 'cancel_job', via: :post
  match 'jobs/:id/mark_as_complete' => 'jobs#mark_as_complete', as: 'mark_as_complete', via: :post

	mount Sidekiq::Web => '/sidekiq'
  match ':status', to: 'errors#show', constraints: {status: /\d{3}/ }, via: :all
  root to: 'high_voltage/pages#show', id: 'splash'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController  
  helper_method :mailbox, :conversation
  before_filter :authenticate_member  

  def index   
    @conversations ||= current_member.mailbox.inbox.all
    @page = "inbox"    
  end
  
  def sentbox
    @conversations ||= current_member.mailbox.sentbox.all
    @page = "sentbox"    
    render :index
  end
  
  def trashbin     
    @conversations ||= current_member.mailbox.trash.all
    @page = "trashbin"    
    render :index   
  end
  
  def new
    if params[:user].present?
      user = User.find(params[:user])
      @recipient_ids = [user.id]
      @recipient_names = [user.name]
    elsif params[:contractor].present?
      contractor = Contractor.find(params[:contractor])
      @recipient_ids = [contractor.id]
      @recipient_names = [contractor.name]
    end
  end

  def create        
    recipient_ids = conversation_params(:recipient_ids).split(',')    
    if current_member.user?
      recipients = Contractor.where(id: recipient_ids).all
    else
      recipients = User.where(id: recipient_ids).all
    end
    conversation = current_member.send_message(recipients, *conversation_params(:body, :subject)).conversation
    redirect_to conversation_path(conversation)
  end
  
  def show
    conversation.mark_as_read(current_member)
  end  

  def reply
    current_member.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_member)
    redirect_to :back
  end

  def untrash
    conversation.untrash(current_member)
    redirect_to :back
  end
  
  def empty_trash
    current_member.mailbox.trash.each do |conversation|
      conversation.receipts_for(current_member).update_all(:deleted => true)
    end
    redirect_to :conversations
  end

  private
    def authenticate_member
      unless member_signed_in?
        redirect_to new_user_registration_path, notice: 'You have to sign up or sign in to access that page.'
      end
    end

    def mailbox
      @mailbox ||= current_member.mailbox
    end

    def conversation
      @conversation ||= mailbox.conversations.find(params[:id])
    end

    def conversation_params(*keys)
      fetch_params(:conversation, *keys)
    end

    def message_params(*keys)
      fetch_params(:message, *keys)
    end

    def fetch_params(key, *subkeys)
      params[key].instance_eval do
        case subkeys.size
        when 0 then self
        when 1 then self[subkeys.first]
        else subkeys.map{|k| self[k] }
        end
      end
    end    
end

app/views/conversations/_conversation.html.erb
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Sent at</th>
                <th>Sender</th>
                <th>Subject</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>            
            <% @conversations.each do |conversation| %>
            <tr class=<%= "#{'unread' if conversation.is_unread?(current_member)}" %>>                
                <td><%= conversation.id %></td>
                <td><%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %></td>
                <td>
                    <%= message_sender(conversation, @page) %>
                </td>
                <td><%= link_to conversation.subject, conversation_path(conversation) %></td>                
                <td>
                <%= conversation.is_completely_trashed?(current_member) ? link_to('Untrash', untrash_conversation_path(conversation), method: :post) : link_to('Move to trash', trash_conversation_path(conversation), method: :post) %>                 
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/conversations/_form.html.erb
<%= simple_form_for :conversation, url: :conversations do |f| %>
  <%= f.input :recipient_ids, :as => :hidden, :input_html => { :value => @recipient_ids } %>
  <%= f.input :recipient_names, label: "Send To", :input_html => { :value => @recipient_names } %>
  <%= f.input :subject %>
  <%= f.input :body, as: :text %>
  <div class="form-actions">
    <%= f.button :submit, 'Send Message', class: 'btn-primary' %>
    <%= submit_tag 'Clear Box', type: :reset, class: 'btn btn-danger' %>    
  </div>
<% end %>

<script type="text/javascript">
    $("form.simple_form.conversation").validate({
        debug: true,
        rules: {
            "conversation[subject]": {required: true},
            "conversation[body]": {required: true}
        },
        submitHandler: function(form) {
            form.submit();
        }
    });
</script>

app/views/conversations/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">
    <ul class="nav nav-sidebar">        
        <li class=<%= 'active' if @page == 'inbox' %>>
            <%= link_to "Inbox  #{@count if @count != 0}", conversations_path %>
        </li>
        <li class=<%= 'active' if @page == 'sentbox' %>>
            <%= link_to 'Outbox', sentbox_conversations_path %>
        </li>
        <li class=<%= 'active' if @page == 'trashbin' %>>
            <%= link_to 'Trash', trashbin_conversations_path %>
        </li>
    </ul>
</div>

app/views/conversations/index.html.erb
<div class="container-fluid">
    <div class="row row-offcanvas row-offcanvas-left">
        <%= render 'sidebar' %>
        <div class="col-sm-9 col-md-10 main">
            <!--toggle sidebar button-->
            <p class="visible-xs">
                <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">
                    <i class="glyphicon glyphicon-chevron-left"></i>
                </button>
            </p>
            <%= render 'conversation' %>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('[data-toggle=offcanvas]').click(function() {
            $('.row-offcanvas').toggleClass('active');
        });
    }); 
</script>

app/views/conversations/new.html.erb
<div class="container-fluid">
    <div class="row row-offcanvas row-offcanvas-left">
        <%= render 'sidebar' %>
        <div class="col-sm-9 col-md-10 main">
            <p class="visible-xs">
                <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">
                    <i class="glyphicon glyphicon-chevron-left"></i>
                </button>
            </p>
            <h1>Send Message</h1>
            <%= render 'form' %>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('[data-toggle=offcanvas]').click(function() {
            $('.row-offcanvas').toggleClass('active');
        });
    }); 
</script>

app/views/conversations/show.html.erb
<div class="container-fluid">
    <div class="row row-offcanvas row-offcanvas-left">
        <%= render 'sidebar' %>
        <div class="col-sm-9 col-md-10 main">
            <p class="visible-xs">
                    <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                    </button>
                </p>
            <h1><%= conversation.subject %></h1>
            <ul>
              <%= content_tag_for(:li, conversation.receipts_for(current_member).order('created_at')) do |receipt| %>
                <% message = receipt.message %>    
                <p><%= message.sender.name %></p>
                <p><%= message.body %></p>
                <p>Sent <%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %></p>
              <% end %>
            </ul>    
            <%= render 'messages/form', conversation: conversation %>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('[data-toggle=offcanvas]').click(function() {
            $('.row-offcanvas').toggleClass('active');
        });
    }); 
</script>