config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  concern :uploadable do
    resources :uploads, only: [:new, :create]
  end

  concern :messageable do
    resources :messages
  end

  concern :reviewable do
    resource :review, only: [:new, :create, :edit, :update, :destroy]
  end

  def api_endpoints
    devise_for :users, controllers: { registrations: 'api/v1/users/registrations',
                                           sessions: 'api/v1/sessions' }

    devise_for :contractors, controllers: { registrations: 'api/v1/contractors/registrations',
                                                 sessions: 'api/v1/sessions' }

    concern :reviewable do
      resource :review, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :contractors, only: [:index, :show] do
      resource :gallery, only: :show
    end

    resources :users, only: [:show],
                  concerns: [:uploadable, :messageable],
                  defaults: { uploadable: 'user',
                             messageable: 'user' }

    resources :jobs, concerns: [:uploadable, :reviewable],
                     defaults: { uploadable: 'job',
                   reviewable: 'job' } do
      resources :bids, only: [:create, :show, :update, :destroy]
      resource :review
    end

    resources :examples, concerns: [:uploadable],
                         defaults: { uploadable: 'example' }

    resource :search, only: :create

    devise_scope :user do
      match 'users/token_reset' => 'sessions#token_reset', via: :post
    end

    devise_scope :contractor do
      match 'contractors/token_reset' => 'sessions#token_reset', via: :post
    end

    match 'categories' => 'contractors#categories', as: 'contractor_categories', via: :get
    match 'bids/:id/accept' => 'bids#accept_bid', as: 'accept_bid', via: :post
    match 'bids/:id/reject' => 'bids#reject_bid', as: 'reject_bid', via: :post
    match 'jobs/:id/resume_search' => 'jobs#resume_search', as: 'resume_search', via: :post
    match 'jobs/:id/cancel_job' => 'jobs#cancel_job', as: 'cancel_job', via: :post
    match 'jobs/:id/mark_as_complete' => 'jobs#mark_as_complete', as: 'mark_as_complete', via: :post
  end

  if Rails.env.staging?
    namespace :api, path: '/', constraints: { subdomain: 'api.staging' }, defaults: { format: :json } do
      namespace :v1 do
        api_endpoints
      end
    end
  else
    namespace :api, path: '/', constraints: { subdomain: 'api' }, defaults: { format: :json } do
      namespace :v1 do
        api_endpoints
      end
    end
  end

	devise_for :users, controllers: { registrations: 'users/registrations',
                                         sessions: 'sessions' }

	devise_for :contractors, controllers: { registrations: 'contractors/registrations',
                                               sessions: 'sessions' }

  resources :users, only: [:show],
                concerns: [:uploadable, :messageable],
                defaults: { uploadable: 'user', messageable: 'user' }

  resources :contractors, only: [:show, :index],
                      concerns: [:uploadable, :messageable],
                      defaults: { uploadable: 'contractor', messageable: 'contractor' } do
    resource :gallery, only: :show
  end

  resources :jobs, concerns: [:uploadable, :reviewable],
                   defaults: { uploadable: 'job',
                               reviewable: 'job' } do
    resources :bids, only: [:create, :show, :update, :destroy]
    resource :review
  end

  resources :examples, concerns: [:uploadable],
                       defaults: { uploadable: 'example' }

  resources :uploads, only: :destroy

  resources :bids, only: :destroy

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :sentbox
      get :trashbin
      post :empty_trash
    end
  end

  resource :contact, only: [:new, :create]
  resource :search, only: :show

  match 'bids/:id/accept' => 'bids#accept_bid', as: 'accept_bid', via: :post
  match 'bids/:id/reject' => 'bids#reject_bid', as: 'reject_bid', via: :post
  match 'jobs/:id/resume_search' => 'jobs#resume_search', as: 'resume_search', via: :post
  match 'jobs/:id/cancel_job' => 'jobs#cancel_job', as: 'cancel_job', via: :post
  match 'jobs/:id/mark_as_complete' => 'jobs#mark_as_complete', as: 'mark_as_complete', via: :post

	mount Sidekiq::Web => '/sidekiq'
  match ':status', to: 'errors#show', constraints: {status: /\d{3}/ }, via: :all
  root to: 'high_voltage/pages#show', id: 'splash'
end

app/models/job.rb
class Job < ActiveRecord::Base

  include JobValidations
  include PgSearch
  include GlobalConcerns

  scope :with_contractor, ->(contractor_id) { where('contractor_id = ?', contractor_id) }

  belongs_to :user
  belongs_to :contractor

  geocoded_by :address
  validates :address, presence: true

  has_one :review, as: :reviewable

  has_many :bids, dependent: :destroy

  validates :bidding_period, allow_blank: true,
                                    date: { after: Proc.new { Date.today },
                                          message: 'Must be a future date' },
                                      if: Proc.new { |o| o.new_record? }


  before_validation :add_default_location, if: Proc.new { |j| j.address.blank?  }
  def add_default_location
    self.address = self.user.address
    self.longitude = self.user.longitude
    self.latitude = self.user.latitude
  end

  def has_coordinates?
    longitude.present? && latitude.present?
  end

  def status
    state.to_s.humanize.upcase
  end

  # State manager to handle how jobs transition

  include AASM

  aasm column: :state, whiny_transitions: false, requires_new_transaction: false do
    state :searching, initial: true
    state :in_progress
    state :complete
    state :cancelled

    event :activate, before: :set_contractor do
      transitions to: :in_progress
    end

    event :resume_search, before: :reset_contractors  do
      transitions from: [:in_progress, :complete, :cancelled], to: :searching
    end

    event :mark_as_complete do
      transitions from: [:in_progress], to: :complete
    end

    event :cancel, before: :cancel_job do
      transitions from: [:searching, :in_progress], to: :cancelled
    end
  end

  def set_contractor(this_bid)
    reset_contractors
    self.contractor = this_bid.contractor
    this_bid.update_columns(rejected: false, accepted: true)
  end

  def cancel_job
    self.bids.each do |b|
      bid_reset(b, false, true)
    end
    # self.contractor_id = nil
  end

  def reset_contractors
    self.bids.each do |b|
      bid_reset(b, false, false)
    end
    self.contractor_id = nil
  end

  def bid_reset(b, accept, reject)
    b.update!(accepted: accept, rejected: reject)
  end
end

app/controllers/api/v1/jobs_controller.rb
class API::V1::JobsController < API::BaseController
  before_action :authenticate, except: [:index, :show]

  before_action :set_job, only: [:show, :edit, :update, :destroy,
                                 :resume_search, :mark_as_complete, :cancel_job]

  before_action :ensure_permission, only: [:edit, :update, :destroy, :resume_search,
                                           :mark_as_complete, :cancel_job]


  def index
    @jobs = Job.all.includes(:uploads, :bids).order(updated_at: :desc)
               .page(request.headers['Page']).per(request.headers['Per'])

    if category = request.headers['Category']
      @jobs = Job.relevant_categories(category).includes(:uploads, :bids)
                 .order(updated_at: :desc)
                 .page(request.headers['Page'])
                 .per(request.headers['Per'])
    end
  end

  def show
    @bids = @job.bids.where(rejected: false)
                .order(updated_at: :desc)
                .page(request.headers['Page'])
                .per(request.headers['Per'])
  end

  def new
    @job = @member.jobs.build
    render :new
  end

  def create
    @job = @member.jobs.new(job_params)
    if @job.save
      JobMailer.create(@job).deliver_later
      render :show, status: 201
    else
      render json: @job.errors, status: 422
    end
  end

  def edit
    render :edit
  end

  def update
    if @job.update(job_params)
      JobMailer.update(@job).deliver_later
      render :show, status: 202
    else
      render json: @job.errors, status: 422
    end
  end

  def destroy
    @job.destroy
    render json: {}, status: 204
  end

  def resume_search
    @job.resume_search!
    render :show, status: 202
  end

  def mark_as_complete
    @job.mark_as_complete!
    if @job.contractor_id.nil?
      render :show, status: 202
    else
      @review = Review.new(reviewable: @job, reviewerable: @job.user)
      render 'api/v1/reviews/new'
    end
  end

  def cancel_job
    @job.cancel!
    if @job.contractor_id.nil?
      render json: :show, status: 204
    else
      @review = Review.new(reviewable: @job, reviewerable: @job.user)
      render 'api/v1/reviews/new'
    end
  end

  private
    def authenticate
      authenticate_token || render_unauthorized
    end

    def authenticate_token
      member_email  = request.headers['Email'].presence
      @member       = member_email && (User.find_by(email: request.headers['Email']) || Contractor.find_by(email: request.headers['Email']))

      authenticate_with_http_token do |token, options|
        if @member && Devise.secure_compare(@member.authentication_token, token)
          return @member
        end
      end
    end

    def render_unauthorized
      self.headers['WWW-Authenticate'] = 'Token realm="Jobs"'
      render json: 'Bad Credentials', status: 401
    end

    def set_job
      @job = Job.find(params[:id])
    end

    def ensure_permission
      if @member == @job.user
        return
      else
        render json: 'Access denied.', status: 403
      end
    end

    def job_params
      params.require(:job).permit(:address, :longitude, :latitude,
                                  :title, :bidding_period, :description, { categories: [] })
    end
  end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:edit, :update, :destroy, :resume_search,
                                 :mark_as_complete, :cancel_job]

  before_action :user_check, only: [:edit, :update, :destroy, :resume_search,
                                    :mark_as_complete, :cancel_job]

  before_action :new_job_check, only: [:new, :create]

  def index
    respond_to do |format|
      format.html
      format.json { render json: JobDatatable.new(view_context) }
    end
  end

  def show
    @job = Job.includes(uploads: :uploadable).find(params[:id])
    @bids = @job.bids.where(rejected: false)
                     .order(updated_at: :desc)
                     .page(params[:bids])
                     .per(5)
  end

  def new
    @job = current_user.jobs.build
  end

  def create
    @job = current_user.jobs.new(job_params)
    if @job.save
      JobMailer.create(@job).deliver_later
      flash[:notice] = 'Job was successfully created.'
      redirect_to @job
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @job.update(job_params)
      JobMailer.update(@job).deliver_later
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: "'#{ @job.title }' was successfully deleted" }
      format.js
    end
  end

  def resume_search
    @job.resume_search!
    redirect_to @job, notice: "Contractor search for '#{ @job.title }' has been resumed. Please check the job's bids."
  end

  def mark_as_complete
    @job.mark_as_complete!
    if @job.contractor_id.nil?
      redirect_to current_user, notice: "Your job '#{ @job.title }' has been marked as complete."
    elsif @job.review.nil?
      redirect_to new_job_review_path(@job)
    else
      redirect_to edit_job_review_path(@job)
    end
  end

  def cancel_job
    @job.cancel!
    if @job.contractor_id.nil?
      redirect_to current_user, notice: "Your job '#{ @job.title }' has been cancelled."
    elsif @job.review.nil?
      redirect_to new_job_review_path(@job)
    else
      redirect_to edit_job_review_path(@job)
    end
  end

  private
    def user_check
      unless current_user == @job.user
        redirect_to current_member || root_path, alert: 'Access denied.'
      end
    end

    def new_job_check
      unless user_signed_in?
        redirect_to current_member || root_path, alert: 'Access denied.'
      end
    end

    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:state, :address, :longitude, :latitude, :phone,
                                  :title, :bidding_period, :description, { categories: [] })
    end
end

app/helpers/jobs_helper.rb
module JobsHelper

	# def job_duration(job)
	# 	"#{ pluralize(job.duration, job.duration_unit.singularize) }"  	
 #  end

  def job_bid_duration(job)
  	if !job.bidding_period.nil?
	  	if job.bidding_period > Date.today
	  		"| Bidding period ends in #{ time_ago_in_words(job.bidding_period) }"
	  	else
	  		"| Bidding period ended #{ time_ago_in_words(job.bidding_period) } ago"
	  	end
	  else
	  	"| This job post has no expiration"
	  end
  end
end

app/views/jobs/_bid_panel.html.erb
<table class="table table-striped table-hover table-bordered text-center">
  <thead class="lead">
    <td>Contractor</td>
    <td>Cost</td>
    <td>Attachments</td>
    <td>Updated</td>
    <td></td>
  </thead>
  <tbody>
	  <% @bids.each do |bid| %>
	    <tr class="<%= bid.accepted? ? 'success' : '' %>">
			  <td><%= link_to bid.contractor.company_name,
			  								bid.contractor,
			  								class: 'unstyled-link' %></td>
			  <td>$<%= bid.cost %></td>
        <% if bid.pdf.present? %>
          <td>
            <%= link_to "#{ bid.pdf_file_name }", bid.pdf.url, class: 'unstyled-link', target: '_blank' %>
          </td>
        <% end %>
			  <td><%= time_ago_in_words(bid.updated_at)  %> ago</td>
        <td>
          <ul class="list-inline">
            <li><%= link_to ' Accept', accept_bid_path(bid),
                                       class: 'btn btn-success fa fa-lg fa-check-square-o',
                                      method: :post %></li>
            <li><%= link_to ' Reject', reject_bid_path(bid),
                                       class: 'btn btn-danger fa fa-lg fa-times-circle-o',
                                      method: :post %></li>
            <li>
                <%= link_to 'Send Message', new_conversation_path(:contractor => bid.contractor), class: 'btn btn-primary' %>
            </li>
          </ul>
        </td>
		  </tr>
	  <% end %>
  </tbody>
</table>

app/views/jobs/_contractor_job_buttons.html.erb
<% if (request.fullpath).include?('/contractors') %>
  <%= link_to job_path(job), class: 'hidden-xs hidden-sm btn btn-primary pull-right' do %>
    View Details
  <% end %>
<% end %>

app/views/jobs/_job_category_panel.html.erb
<ul class="list-inline categories">
  <% job.categories.each do |c| %>
     <li>
       <span class="label label-<%= %w(default primary success info warning danger).sample %>">
        <%= c %>
       </span>
     </li>
  <% end %>
 </ul>

app/views/jobs/_job_footer_panel.html.erb
<div class="panel-footer">
  <%= "Updated #{ time_ago_in_words(job.updated_at) } ago" %> by
  <%= link_to "#{ owner.fullname }", owner, class: 'unstyled-link' %>
  <%= "| Approx. #{ current_contractor.distance_from(job).round(1) } miles away" if (contractor_signed_in? && job.is_a?(Job) && job.has_coordinates?) %>
  <%= job_bid_duration(job) if job.is_a?(Job) %>
</div>

app/views/jobs/_job_panel.html.erb
<div class="panel panel-default" id="job-<%= job.id %>">
  <div class="panel-heading">
    <%= link_to job, class: 'unstyled-link' do %>
      <p class="panel-title text-center">
        <%= job.title %>
      </p>
    <% end %>
    <h4>
      <%= render 'jobs/job_state_buttons', job: job if current_user == job.user %>
      <%= render 'jobs/contractor_job_buttons', job: job if contractor_signed_in? %>
      Status: <%= job.status %> <%= "(#{ pluralize(job.bids.count, 'bid') })" if job.searching? %>
      <% if job.contractor %>
      with <%= link_to job.contractor.company_name, job.contractor, class: 'unstyled-link' %>
      <% end %>
      <%= render partial: 'jobs/job_category_panel', locals: { job: job } %>
    </h4>
  </div>

  <div class="panel-body">
    <% if contractor_signed_in? %>
      <div class="col-xs-12 col-sm-12 col-md-12" id="job-<%= job.id %>">
        <%= render 'bids/form', job: job %>
      </div>
    <% end %>
    <div class="col-xs-12 text-center">
      <% if job.uploads.count > 0 %>
        <div class="links text-center">
          <ul class="list-inline">
            <%= render partial: 'galleries/gallery_list',
                    collection: job.uploads,
                            as: :image,
                        locals: { owner: job.user } %>
          </ul>
          <hr>
        </div>
        <%= render 'layouts/gallery_lightbox' %>
      <% elsif !job.cancelled? && job.user == current_user %>
        <h4>
          <%= link_to 'Upload pics', new_job_upload_path(job), class: 'unstyled-link' %>
        </h4>
        <hr>
      <% end %>
    </div>

    <% if params[:controller] == 'jobs' %>
      <div class="col-xs-12 col-md-4 text-center">
        <!-- <hr class="visible-xs visible-sm"> -->
        <span class="hidden latitude"><%= job.latitude %></span>
        <span class="hidden longitude"><%= job.longitude %></span>
        <br><br>
        <div class="map_canvas"></div>
        <br>
        <%= link_to "http://maps.google.com/?q=#{ job.address }",
            class: 'google_links',
          target: "_blank" do %>
            <%= fa_icon 'external-link', title: 'View in Google Maps' %>
            View in Google Maps
        <% end %>
      </div>
    <% end %>

      <div  class="col-xs-12 <%= params[:controller] == 'jobs' ? 'col-md-8' : '' %>">
        <h5>

          <%= (request.fullpath).include?('jobs') ?
                                job.description :
                                truncate(job.description, length: 200) %>
                              </h5>
      </div>
    </div>
    <%= render partial: 'jobs/job_footer_panel', locals: { job: job, owner: job.user } %>
</div>

app/views/jobs/_job_review.html.erb
<strong>Quality:</strong>
<%= job.review.quality %>/10
<br>
<strong>Cost:</strong>
<%= job.review.cost %>/10
<br>
<strong>Timeliness:</strong>
<%= job.review.timeliness %>/10
<br>
<strong>Professionalism:</strong>
<%= job.review.professionalism %>/10
<br>
<strong>Likelihood to recommend:</strong>
<%= job.review.recommendation %>/10

app/views/jobs/_job_state_buttons.html.erb
<ul class="list-inline pull-right">
  <% if !job.searching? %>
    <% if !job.cancelled? %>
      <% unless job.complete? %>
      <li>
        <%= link_to mark_as_complete_path(job), title: 'Mark as complete',
                                               method: :post do %>
          <%= fa_icon 'check-square-o lg', class: 'text-success' %>
        <% end %>
      </li>
      <% end %>
    <% end %>

    <li>
      <%= link_to resume_search_path(job), title: 'Resume bid search',
                                          method: :post do %>
        <%= fa_icon 'history lg' %>
      <% end %>
    </li>
  <% end %>

  <% unless job.complete? %>
    <li>
      <%= link_to edit_job_path(job), title: 'Edit job details' do %>
        <%= fa_icon 'edit lg' %>
      <% end %>
    </li>
  <% end %>
  
  <% unless job.cancelled? %>
    <li>
      <%= link_to cancel_job_path(job), title: 'Cancel job',
                                       method: :post do %>
        <%= fa_icon 'minus-square-o lg', class: 'text-danger' %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/jobs/_lat_lon_inputs.html.erb
<% @longitude = job.persisted? ? job.longitude : current_user.longitude %>
<% @latitude = job.persisted? ? job.latitude : current_user.latitude %>

<ul class="list-inline">
  <li>
    <%= f.input :latitude, disabled: true,
                         input_html: { value: @latitude,
                                       class: 'latitude',
                                        data: { geo: 'lat' } } %>
    <%= f.input :latitude, as: :hidden,
                   input_html: { value: @latitude,
                                 class: 'latitude',
                                  data: { geo: 'lat' } } %>
  </li>
  <li>
    <%= f.input :longitude, disabled: true,
                          input_html: { value: @longitude,
                                        class: 'longitude',
                                         data: { geo: 'lng' } } %>
    <%= f.input :longitude, as: :hidden,
                    input_html: { value: @longitude,
                                  class: 'longitude',
                                   data: { geo: 'lng' } } %>
  </li>
</ul>

app/views/jobs/destroy.js.erb
$('#job-<%= @job.id %>').css( "color", "#bc0303" )
										.css( "font-weight", "bold");
$('#job-<%= @job.id %>').fadeOut(250);

app/views/jobs/edit.html.erb
<% title "Edit Job" %>

<div class="container">
	<%= render partial: 'layouts/job_form', 
							locals: { member: @user, 
													 job: @job, 
													type: 'job' } %>
</div>
<hr>
<div class="row">
	<div class="form-actions-submit">
    <%= link_to 'Back', current_user, class: 'submit' %>
	</div>
</div>

app/views/jobs/index.html.erb
<% title "#{ params[:search].singularize } Jobs" if params[:search] %>

<div class="container">
  <div class="row col-md-10 col-md-offset-1 col-sm-12">
    <span  class="text-center">
      <h1 class="lead">Open Jobs: <%= params[:scoped] %></h1>
      <p >Browse <%= link_to 'Contractors', contractors_path, class: 'unstyled-link' %></p>
    </span>
    <div id="job_index">
      <table id="jobs-table" data-source="<%= jobs_path(scoped: params[:scoped], format: :json) %>" class="display responsive no-wrap table table-hover table-striped">
        <thead>
          <td>Image</td>
          <td>Title</td>
          <td>Categories</td>
          <td>Description</td>
        </thead>
      </table>
    </div>
  </div>
</div>

app/views/jobs/index.js.erb
$('#paginator-jobs-top').html('<%= escape_javascript(paginate(@jobs, remote: true, 
																							  										  theme: "twitter-bootstrap-3",
																					                       param_name: "jobs")) %>');
$('#paginator-jobs-bottom').html('<%= escape_javascript(paginate(@jobs, remote: true, 
																								  										   theme: "twitter-bootstrap-3",
																						                        param_name: "jobs")) %>');

$('#job_index').html('<%= escape_javascript(render partial: "job_index") %>');

$('body').scrollTo('.pagination', { duration: 300, offset: -150 });

app/views/jobs/new.html.erb
<% title "Post Job" %>

<div class="container">
	<%= render partial: 'layouts/job_form', locals: { job: @job, type: 'job' } %>
	<hr>
	<div class="form-actions-submit">
    <%= link_to 'Back', current_user, class: 'submit' %>
	</div>
</div>

app/views/jobs/show.html.erb
<% title "Job Post" %>

<div class="container">
  <%= render partial: 'layouts/image_modal',
          collection: @job.uploads,
                  as: :upload %>

  <div class="row">
    <% if @job.searching? %>
      <% if @bids.count > 0 && current_user == @job.user %>
        <h3 class="text-center lead">Recent bids for this job</h3>

      <div id="paginator-bids-top" class="text-center">
        <%= render partial: 'layouts/paginator',
                    locals: { context: @bids,
                       context_string: 'bids' } %>
      </div>

        <div class="col-xs-12" id="bids">
          <%= render partial: 'bid_panel'if @job.bids %>
        </div>

        <% elsif @bids.count == 0 && current_user == @job.user %>
          <h3 class="text-center lead">There are no bids for this job</h3>
      <% end %>
    <% end %>

    <div class="col-xs-12">
      <%= render 'job_panel', job: @job %>
    </div>

    <% unless @job.searching? %>
      <h3 class="text-center lead">
        Job is <%= @job.status %>
        <%= link_to " with #{ @job.contractor.company_name }", @job.contractor, class: 'unstyled-link' if @job.contractor %>
      </h3>
      <% if @job.review.present? && !@job.in_progress? %>
        <hr>
        <div class="lead col-lg-6 col-lg-offset-3 col-xs-12">
          <div class="text-center">
            <% if current_user == @job.user %>
              <strong><%= link_to 'Review', job_review_path(@job), class: 'unstyled-link' %></strong><br>
            <% else %>
              <strong>Review</strong><br>
            <% end %>
          </div>
          <%= render "job_review", job: @job %>
          <br><br>
          <strong>Comments</strong>
          <br>
          <%= @job.review.description %>
        </div>
      <% end %>
    <% end %>

    <%= render 'layouts/back_to_profile' %>
  </div>
</div>