config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  concern :uploadable do
    resources :uploads, only: [:new, :create]
  end

  concern :messageable do
    resources :messages
  end

  concern :reviewable do
    resource :review, only: [:new, :create, :edit, :update, :destroy]
  end

  def api_endpoints
    devise_for :users, controllers: { registrations: 'api/v1/users/registrations',
                                           sessions: 'api/v1/sessions' }

    devise_for :contractors, controllers: { registrations: 'api/v1/contractors/registrations',
                                                 sessions: 'api/v1/sessions' }

    concern :reviewable do
      resource :review, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :contractors, only: [:index, :show] do
      resource :gallery, only: :show
    end

    resources :users, only: [:show],
                  concerns: [:uploadable, :messageable],
                  defaults: { uploadable: 'user',
                             messageable: 'user' }

    resources :jobs, concerns: [:uploadable, :reviewable],
                     defaults: { uploadable: 'job',
                   reviewable: 'job' } do
      resources :bids, only: [:create, :show, :update, :destroy]
      resource :review
    end

    resources :examples, concerns: [:uploadable],
                         defaults: { uploadable: 'example' }

    resource :search, only: :create

    devise_scope :user do
      match 'users/token_reset' => 'sessions#token_reset', via: :post
    end

    devise_scope :contractor do
      match 'contractors/token_reset' => 'sessions#token_reset', via: :post
    end

    match 'categories' => 'contractors#categories', as: 'contractor_categories', via: :get
    match 'bids/:id/accept' => 'bids#accept_bid', as: 'accept_bid', via: :post
    match 'bids/:id/reject' => 'bids#reject_bid', as: 'reject_bid', via: :post
    match 'jobs/:id/resume_search' => 'jobs#resume_search', as: 'resume_search', via: :post
    match 'jobs/:id/cancel_job' => 'jobs#cancel_job', as: 'cancel_job', via: :post
    match 'jobs/:id/mark_as_complete' => 'jobs#mark_as_complete', as: 'mark_as_complete', via: :post
  end

  if Rails.env.staging?
    namespace :api, path: '/', constraints: { subdomain: 'api.staging' }, defaults: { format: :json } do
      namespace :v1 do
        api_endpoints
      end
    end
  else
    namespace :api, path: '/', constraints: { subdomain: 'api' }, defaults: { format: :json } do
      namespace :v1 do
        api_endpoints
      end
    end
  end

	devise_for :users, controllers: { registrations: 'users/registrations',
                                         sessions: 'sessions' }

	devise_for :contractors, controllers: { registrations: 'contractors/registrations',
                                               sessions: 'sessions' }

  resources :users, only: [:show],
                concerns: [:uploadable, :messageable],
                defaults: { uploadable: 'user', messageable: 'user' }

  resources :contractors, only: [:show, :index],
                      concerns: [:uploadable, :messageable],
                      defaults: { uploadable: 'contractor', messageable: 'contractor' } do
    resource :gallery, only: :show
  end

  resources :jobs, concerns: [:uploadable, :reviewable],
                   defaults: { uploadable: 'job',
                               reviewable: 'job' } do
    resources :bids, only: [:create, :show, :update, :destroy]
    resource :review
  end

  resources :examples, concerns: [:uploadable],
                       defaults: { uploadable: 'example' }

  resources :uploads, only: :destroy

  resources :bids, only: :destroy

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :sentbox
      get :trashbin
      post :empty_trash
    end
  end

  resource :contact, only: [:new, :create]
  resource :search, only: :show

  match 'bids/:id/accept' => 'bids#accept_bid', as: 'accept_bid', via: :post
  match 'bids/:id/reject' => 'bids#reject_bid', as: 'reject_bid', via: :post
  match 'jobs/:id/resume_search' => 'jobs#resume_search', as: 'resume_search', via: :post
  match 'jobs/:id/cancel_job' => 'jobs#cancel_job', as: 'cancel_job', via: :post
  match 'jobs/:id/mark_as_complete' => 'jobs#mark_as_complete', as: 'mark_as_complete', via: :post

	mount Sidekiq::Web => '/sidekiq'
  match ':status', to: 'errors#show', constraints: {status: /\d{3}/ }, via: :all
  root to: 'high_voltage/pages#show', id: 'splash'
end

app/controllers/api/v1/reviews_controller.rb
class API::V1::ReviewsController < API::V1::VersionController
  before_action :authenticate
  before_action :set_job
  before_action :get_reviewable, only: [:new, :create, :edit, :update]
  before_action :get_reviewerable, only: [:new, :create, :edit, :update]

  before_action :ensure_permission, except: [:show]


  def new
    if @job.review
      @job.review.destroy
    end
    @review = Review.new(reviewable: @job, reviewerable: @job.user)
  end

  def create
    @review = Review.create(review_params)
    @review.reviewable   = @reviewable
    @review.reviewerable = @reviewerable
    if @review.save
      render :show
    else
      render :new, json: { error: "#{ @review.errors.full_messages.to_sentence }" }, status: 422
    end
  end

  def show
    @review = @job.review
  end

  def edit
    @review = @job.review
  end

  def update
    @review = @job.review
    if @review.update(review_params)
      render :show, status: 200
    else
      render :edit, error: "#{ @review.errors.full_messages.to_sentence }", status: 422
    end
  end

  def destroy
    @review = @job.review
    if @review
      @review.destroy
      head :no_content, status: 204
    else
      render json: {}, status: 404
    end
  end

  private
    def authenticate
      authenticate_token || render_unauthorized
    end

    def authenticate_token
      member_email  = request.headers['Email'].presence
      @member       = member_email && (User.find_by(email: request.headers['Email']) || Contractor.find_by(email: request.headers['Email']))

      authenticate_with_http_token do |token, options|
        if @member && Devise.secure_compare(@member.authentication_token, token)
          return @member
        end
      end
    end

    def render_unauthorized
      self.headers['WWW-Authenticate'] = 'Token realm="Jobs"'
      render json: 'Bad Credentials', status: 401
    end

    def ensure_permission
      if @member == @job.user
        return
      else
        render json: 'Access denied.', status: 403
      end
    end

    def get_reviewerable
      @reviewerable = @member
    end

    def get_reviewable
      @reviewable = params[:reviewable].classify.constantize.find(reviewable_id)
    end

    def reviewable_id
      params[(params[:reviewable].singularize + '_id').to_sym]
    end

    def set_job
      @job = Job.find(params[:job_id])
    end

    def review_params
      params.require(:review).permit(:quality, :cost, :timeliness, :professionalism, :recommendation, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_job
  # before_action :set_review, only: [:edit, :update, :destroy]
  before_action :get_reviewable, only: [:new, :create, :edit, :update]
  before_action :get_reviewerable, only: [:new, :create, :edit, :update]
  # respond_to :html

  def new
    @review = Review.new
  end

  def create
    @review = Review.create(review_params)
    @review.reviewable   = @reviewable
    @review.reviewerable = @reviewerable
    @review.contractor = @reviewable.contractor
    if @review.save
      flash[:notice] = 'Review was successfully created.'
      redirect_to job_review_path(@job)
    else
      render 'new', error: "#{ @review.errors.full_messages.to_sentence }"
    end
  end

  def show
    @review = @job.review
  end

  def edit
    @review = @job.review
  end

  def update
    @review = @job.review
    if @review.update(review_params)
      redirect_to job_review_path(@job), notice: 'Review was successfully updated.'
    else
      render 'edit', error: "#{ @review.errors.full_messages.to_sentence }"
    end
  end

  def destroy
    @review = @job.review
    @review.destroy
    respond_to do |format|
      # format.html { redirect_to current_user, notice: "'Review for #{ @job.title }' was successfully deleted" }
      format.js
    end
  end

  private

    def get_reviewerable
      @reviewerable = current_user || current_contractor
    end

    def get_reviewable
      @reviewable = params[:reviewable].classify.constantize.find(reviewable_id)
    end

    def reviewable_id
      params[(params[:reviewable].singularize + '_id').to_sym]
    end

    def set_job
      @job = Job.find(params[:job_id])
    end


    def review_params
      params.require(:review).permit(:quality, :cost, :timeliness, :professionalism, :recommendation, :description)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="row authform">
  <%= simple_form_for @review, url: job_review_path, html: { autocomplete: 'off' } do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :quality, input_html: { id: 'review_quality' } %>
      <%= f.input :cost, input_html: { id: 'review_cost' } %>
      <%= f.input :timeliness, input_html: { id: 'review_timeliness' } %>
      <%= f.input :professionalism, input_html: { id: 'review_professionalism' } %>
      <%= f.input :recommendation, label: 'How likely are you to recommend this contractor to other people?',
                              input_html: { id: 'review_recommendation' } %>
      <%= f.input :description, as: :text,
                             label: 'Comments (optional)',
                       placeholder: 'Maximum 2000 characters.',
                        input_html: { rows: '7', maxlength: 2000 } %>
    </div>

    <div class="form-actions text-center">
      <%= f.button :submit, 'Submit review', class: 'btn btn-success' %>
    </div>
  <% end %>
  <br>
  <%= render 'layouts/back_to_profile' %>
</div>

app/views/reviews/_review_panel.html.erb
<div class="panel panel-default" id="review-<%= review.id %>">
  <div class="panel-heading">
    <div class="panel-title">
      <span class="text-center">
        <%= link_to review.reviewable.title, review.reviewable, class: 'unstyled-link' %>: <%= review.reviewable.status %>
        <% if review.reviewable.contractor %>
          with <%= link_to review.reviewable.contractor.company_name, review.reviewable.contractor, class: 'unstyled-link' %>
        <% end %>
      </span>
        <% if current_user == review.reviewerable %>
          <ul class="list-inline pull-right">
            <li>
              <%= link_to edit_job_review_path(review.reviewable) do %>
                  <%= fa_icon 'edit', title: 'Edit',
                                            class: 'pull-right' %>
              <% end %>
            </li>
            <li>
              <%= link_to job_review_path(review.reviewable), method: :delete,
                                                                        remote: true,
                                                                          data: { confirm: 'Are you sure you want to delete this review?' } do %>
                <%= fa_icon 'minus-square-o', title: 'Delete',
                                                    class: 'delete-comment-post pull-right' %>
              <% end %>
            </li>
          </ul>
        <% end %>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-xs-12 col-md-3">
      <%= render partial: "jobs/job_review", locals: { job: review.reviewable } %>
    </div>
    <div class="col-xs-12 col-md-9">
      <%= review.description %>
    </div>
  </div>

  <div class="panel-footer text-center">
    <%= "Updated #{ time_ago_in_words(review.updated_at) } ago " %>
  </div>
</div>

app/views/reviews/_review_tab_pane.html.erb
<div class="<%= (params[:tab] == 'reviews') ?
  'tab-pane fade in active' :
  'tab-pane fade in' %>" id="review">
  <% if @reviews.present? %>
    <%= render 'reviews/reviews' %>
  <% else %>
  <br>
  <h4 class="text-center">No reviews currently on record</h4>
  <% end %>
</div>

app/views/reviews/_reviews.html.erb
<div id="paginator-reviews-top" class="text-center">
  <%= render partial: 'layouts/paginator',
              locals: { context: @reviews,
      context_string: 'reviews' } %>
  </div>

  <div id="reviews">
    <%= render partial: 'reviews/review_panel',
            collection: @reviews,
                    as: :review %>
  </div>

  <div id="paginator-reviews-bottom" class="text-center col-xs-12">
    <%= render partial: 'layouts/paginator',
                locals: { context: @reviews,
                  context_string: 'reviews' } %>
  </div>

app/views/reviews/destroy.js.erb
$('#review-<%= @review.id %>').css( "color", "#bc0303" )
                              .css( "font-weight", "bold");
$('#review-<%= @review.id %>').fadeOut(250);

app/views/reviews/edit.html.erb
<h3 class="lead text-center">
  Edit review for: '<%= link_to @job.title, @job, class: 'unstyled-link' %>'<br>
  Performed by: '<%= link_to @job.contractor.company_name, @job.contractor, class: 'unstyled-link' %>'
</h3>
<%= render 'form' %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Job</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.description %></td>
        <td><%= review.job %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_job_review_path(@job) %>

app/views/reviews/new.html.erb
<h3 class="lead text-center">
  Please review the work
  <%= link_to @job.contractor.company_name, @job.contractor, class: 'unstyled-link' %>
  did on '<%= link_to @job.title, @job, class: 'unstyled-link' %>'
</h3>

<%= render 'form' %>

app/views/reviews/show.html.erb
<p>
  <strong>Job:</strong>
  <%= @review.reviewable.title %>
</p>

<p>
  <strong>Contractor:</strong>
  <%= @review.reviewable.contractor.fullname %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @review.quality %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @review.cost %>
</p>

<p>
  <strong>Timeliness:</strong>
  <%= @review.timeliness %>
</p>

<p>
  <strong>Professionalism:</strong>
  <%= @review.professionalism %>
</p>

<p>
  <strong>Likelihood to recommend</strong>
  <%= @review.recommendation %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @review.description %>
</p>

<%= link_to 'Edit', edit_job_review_path(@job) %> |
<%= link_to 'Back', job_path(@job) %>